### ISSUE TITLE
Thread 'ImportQueueWorker' panicked 

### ISSUE THREAD

**Issue by starit** [chainx-org/ChainX#18]
2019-04-13 06:29:56.660 INFO [runtime|xrml_xsystem] height:22401, blockproducer: 74725dad959ffc248a50c9ccc923f772e5df352bb2423616417c94777177876c (5EhPPKHk...)|name:Facebook

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h6151f83348fe5cb3 (0x561b7cc7731f)
   1: rust_panic_with_hook (0x561b7ce5e1e8)
             at src/libstd/panicking.rs:478
   2: std::panicking::begin_panic::ha17c276b68ef3911 (0x561b7ca37ad4)
   3: <chainx_runtime::xexecutive::Executive<System, Block, Context, Payment, AllModules>>::execute_block::hf28d0b5901e8ead2 (0x561b7ca9ad52)
   4: chainx_runtime::api::dispatch::hbd978dc53fe9f7c9 (0x561b7c9d0a52)
   5: std::panicking::try::do_call::h7ae11b3d4cdfbdfb (0x561b7c45de11)
   6: __rust_maybe_catch_panic (0x561b7ce64579)
             at src/libpanic_unwind/lib.rs:87
   7: substrate_executor::native_executor::safe_call::h13303d24dfa76ef7 (0x561b7c45daf2)
   8: <std::thread::local::LocalKey<T>>::with::hf324c8a2d7642d9b (0x561b7c45d516)
   9: <chainx_executor::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch::hffd4afadc7f37f13 (0x561b7c45ce7c)
  10: <std::thread::local::LocalKey<T>>::with::he29e68a370bece3e (0x561b7c18d316)
  11: <substrate_state_machine::StateMachine<'a, H, B, T, O, Exec>>::execute_aux::h10a9eb4603a2b4ce (0x561b7bfd9ca2)
  12: <substrate_state_machine::StateMachine<'a, H, B, T, O, Exec>>::execute_call_with_native_else_wasm_strategy::h01e29a7158eeac09 (0x561b7c0624b2)
  13: <substrate_state_machine::StateMachine<'a, H, B, T, O, Exec>>::execute_using_consensus_failure_handler::hb71ec0f91bbf6eca (0x561b7c03ef11)
  14: <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state::h39de45a6d010cf78 (0x561b7c10cde1)
  15: <substrate_client::client::Client<B, E, Block, RA>>::lock_import_and_run::{{closure}}::h576be5145f13c396 (0x561b7c30e2be)
  16: <substrate_client::client::Client<B, E, Block, RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h6e2b74ee4ad6ffc3 (0x561b7c2df371)
  17: <substrate_finality_grandpa::import::GrandpaBlockImport<B, E, Block, RA, PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::hbc25775dd83ec082 (0x561b7c1f36f2)
  18: <substrate_consensus_common::import_queue::BlockImportWorker<B, V>>::import_a_batch_of_blocks::h6640ccd940ec190c (0x561b7bf6162b)
  19: std::sys_common::backtrace::__rust_begin_short_backtrace::hc46b607889d60a21 (0x561b7c3f29fe)
  20: std::panicking::try::do_call::hefc70362a4239358 (0x561b7bd9a87d)
  21: __rust_maybe_catch_panic (0x561b7ce64579)
             at src/libpanic_unwind/lib.rs:87
  22: <F as alloc::boxed::FnBox<A>>::call_box::hdf3f10eb1475be8f (0x561b7bdb599e)
  23: call_once<(),()> (0x561b7ce638bd)
             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/liballoc/boxed.rs:759
      start_thread
             at src/libstd/sys_common/thread.rs:14
      thread_start
             at src/libstd/sys/unix/thread.rs:80
  24: start_thread (0x7f32431526da)
  25: __clone (0x7f3242c6388e)
  26: <unknown> (0x0)

Thread 'ImportQueueWorker' panicked at 'All extrinsics should have the correct nonce', runtime/src/xexecutive.rs:183

This is a bug. Please report it at:

        https://github.com/chainx-org/ChainX

**Comment by starit** [comment]
duplicate with https://github.com/chainx-org/ChainX/issues/17
