### ISSUE TITLE
调用sdot提息sdk时报错

### ISSUE THREAD

**Issue by dengrun** [chainx-org/ChainX#20]
{ RpcError: [1012]: Transaction is temporarily banned
    at RpcCoder.checkError (/home/drun/node_modules/@chainx/rpc-provider/lib/coder.js:121:15)
    at RpcCoder.decodeResponse (/home/drun/node_modules/@chainx/rpc-provider/lib/coder.js:87:12)
    at WsProvider.onSocketMessageResult (/home/drun/node_modules/@chainx/rpc-provider/lib/ws/index.js:120:34)
    at W3CWebSocket.onmessage (/home/drun/node_modules/@chainx/rpc-provider/lib/ws/index.js:103:39)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/drun/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/home/drun/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/drun/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at emitOne (events.js:116:13)
    at WebSocketConnection.emit (events.js:211:7)
    at WebSocketConnection.processFrame (/home/drun/node_modules/websocket/lib/WebSocketConnection.js:554:26)
  name: 'RpcError',
  message: '[1012]: Transaction is temporarily banned',
  data: 
   { code: 1012,
     message: 'Transaction is temporarily banned',
     data: undefined } }

**Comment by liuchengxu** [comment]
#21
