### ISSUE TITLE
页面报错

### ISSUE THREAD

**Issue by feilun-feilun** [chainx-org/ChainX#246]
https://dapp-v2.chainx.org/trust  几个菜单相互切换，换几次页面报错，显示如下内容。

Unhandled Rejection (TypeError): Cannot read property 'locks' of undefined
(anonymous function)
src/reducers/assetSlice.js:102
   99 | 
  100 | export const fetchLocks = address => async dispatch => {
  101 |   const api = getChainx()
> 102 |   const locks = await api.query.xStaking.locks(address)
  103 |   dispatch(setLocks(locks.toJSON()))
  104 | }
  105 | 
View compiled
▶ 2 stack frames were collapsed.
(anonymous function)
src/App.js:57
  54 | // dispatch(fetchBondingDuration())
  55 | 
  56 | dispatch(fetchAccountAssets(address))
> 57 | dispatch(fetchLocks(address))
     | ^  58 | dispatch(fetchChainx2NativeAsset(address))
  59 | 
  60 | const api = getChainx()
View compiled
▶ 12 stack frames were collapsed.

Unhandled Rejection (TypeError): Cannot read property 'account' of undefined
(anonymous function)
src/reducers/assetSlice.js:114
  111 | 
  112 | export const fetchChainx2NativeAsset = address => async dispatch => {
  113 |   const api = getChainx()
> 114 |   const asset = await api.query.system.account(address)
  115 |   let nativeAsset = {}
  116 |   for (let [key, value] of asset.data.entries()) {
  117 |     nativeAsset[key] = value.toString()
View compiled
▶ 2 stack frames were collapsed.
(anonymous function)
src/App.js:58
  55 | 
  56 | dispatch(fetchAccountAssets(address))
  57 | dispatch(fetchLocks(address))
> 58 | dispatch(fetchChainx2NativeAsset(address))
     | ^  59 | 
  60 | const api = getChainx()
  61 | let unsubscribeNewHead = null
View compiled
▶ 12 stack frames were collapsed.

**Comment by feilun-feilun** [comment]
F12：部分报错内容如下 
API-WS: DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at WsProvider.connect (https://dapp-v2.chainx.org/static/js/0.chunk.js:157007:158)
    at async WsProvider.connectWithRetry (https://dapp-v2.chainx.org/static/js/0.chunk.js:157029:7)

**Comment by feilun-feilun** [comment]
重现方式：几个菜单间反复切换，“投票选举”菜单内会出现加载的情况，加载一会儿就报错。
截图如下：
![01](https://user-images.githubusercontent.com/49551621/93878062-0dbac400-fd0c-11ea-8985-c9c7d874e25c.png)
![02](https://user-images.githubusercontent.com/49551621/93878066-0f848780-fd0c-11ea-9840-d8634e3442d8.png)
![03](https://user-images.githubusercontent.com/49551621/93878071-10b5b480-fd0c-11ea-82c5-85a25d014346.png)
