### ISSUE TITLE
panicked at 'Transaction has a bad signature'

### ISSUE THREAD

**Issue by icodezjb** [chainx-org/ChainX#418]
- Ubuntu16.04, chainx-2.0.4, 4G内存

- config.json
```
{
  "chain": "mainnet",
  "log-dir": "./log",
  "enable-console-log": false,
  "ws-max-connections":10000,
  "no-mdns": true,
  "validator": false,
  "ws-external":true, 
  "rpc-external": true,
  "log": "info,runtime=info",
  "port": 20222,
  "ws-port": 8087,
  "rpc-port": 8086,
  "pruning": "archive",
  "rpc-cors": "all",
  "execution": "NativeElseWasm",
  "db-cache": 2048,
  "state-cache-size": 2147483648,
  "name": "good",
  "keystore-path": "./keys/sync/keystore",
  "base-path": "./data",
  "bootnodes": []
}
```

- error.log
```
====================

Version: 2.0.4-6cbd6e2-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/381b445ff5751f9f39ec672b623372dff09c276e/library/std/src/panicking.rs:581:17
   2: std::panicking::begin_panic::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: std::panicking::begin_panic
   5: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::execute_extrinsics_with_book_keeping
   6: tracing::span::Span::in_scope
   7: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::execute_block
   8: <chainx_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<<pallet_indices::Module<chainx_runtime::Runtime> as sp_runtime::traits::StaticLookup>::Source,chainx_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<chainx_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<chainx_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<chainx_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<chainx_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<chainx_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<chainx_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<chainx_runtime::Runtime>,chainx_runtime::BaseFilter,chainx_runtime::impls::ChargeExtraFee)>>>>::execute_block
   9: sp_api::runtime_decl_for_Core::execute_block_native_call_generator::{{closure}}
  10: std::thread::local::LocalKey<T>::with
  11: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
  12: sc_executor::wasm_runtime::RuntimeCache::with_instance
  13: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
  14: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
  15: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
  16: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  17: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  18: sp_api::Core::execute_block_with_context
  19: <&sc_service::client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
  20: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
  21: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
  22: sp_consensus::import_queue::import_single_block_metered
  23: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  24: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  25: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
  26: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  27: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  28: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  29: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  30: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  31: std::thread::local::LocalKey<T>::with
  32: futures_executor::local_pool::block_on
  33: tokio::runtime::task::core::Core<T,S>::poll
  34: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  35: tokio::runtime::task::raw::poll
  36: tokio::runtime::blocking::pool::Inner::run
  37: tokio::runtime::context::enter
  38: std::sys_common::backtrace::__rust_begin_short_backtrace
  39: core::ops::function::FnOnce::call_once{{vtable.shim}}
  40: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/381b445ff5751f9f39ec672b623372dff09c276e/library/alloc/src/boxed.rs:1042:9
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/381b445ff5751f9f39ec672b623372dff09c276e/library/alloc/src/boxed.rs:1042:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/381b445ff5751f9f39ec672b623372dff09c276e/library/std/src/sys/unix/thread.rs:87:17
  41: start_thread
  42: clone


Thread 'tokio-runtime-worker' panicked at 'Transaction has a bad signature', /home/eos/.cargo/git/checkouts/substrate-7e08433d4c370a21/11ace4e/frame/executive/src/lib.rs:361

```

- chainx.log
```
2020-12-07 13:28:48:861 WARN tokio-runtime-worker telemetry  ❌ Error while dialing /dns/stats.chainx.org/tcp/1024/x-parity-ws/%2Fsubmit%2F: Custom { kind: Other, error: Other(B(A(Transport(Underlying(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))))) }
2020-12-07 13:28:49:821 INFO tokio-runtime-worker substrate  ⚙️  Syncing  0.0 bps, target=#178171 (8 peers), best: #177850 (0xef5f…6909), finalized #177849 (0x1913…fb14), ⬇ 42.9kiB/s ⬆ 1.8kiB/s
2020-12-07 13:28:51:090 INFO unnamed parity_ws::io  Accepted a new tcp connection from 47.89.12.202:48810.
2020-12-07 13:28:51:556 INFO tokio-runtime-worker frame_executive  execute_block; block=Block { header: Header { parent_hash: 0x191380def78ba57f3a3e934e38f4977261c195ab3217956347dc78fffc76fb14, number: 177850, state_root: 0xceb79ec436fe107a6b75aee7e7e626a56f1a6a63f15ebab8d95f23123405ecb9, extrinsics_root: 0xe65569b3f8727f3ca0c60688710944884c67d5910f58154c10bd6c1292cc591f, digest: Digest { logs: [DigestItem::PreRuntime([66, 65, 66, 69], [3, 16, 0, 0, 0, 71, 158, 247, 15, 0, 0, 0, 0, 244, 170, 109, 177, 18, 103, 252, 139, 201, 236, 228, 168, 213, 204, 150, 97, 193, 248, 37, 72, 119, 39, 115, 117, 137, 33, 132, 51, 136, 16, 72, 114, 216, 84, 161, 84, 108, 114, 150, 182, 124, 223, 2, 4, 12, 62, 137, 86, 205, 148, 96, 201, 92, 77, 240, 68, 196, 112, 121, 140, 153, 150, 208, 2, 241, 160, 203, 70, 122, 18, 38, 147, 135, 47, 205, 64, 8, 224, 187, 208, 221, 73, 169, 173, 156, 62, 139, 243, 127, 225, 51, 189, 4, 128, 243, 2])] } }, extrinsics: [UncheckedExtrinsic(None, Call::Timestamp(set(1607316906000,))), UncheckedExtrinsic(Some((Address::Id(31000d19a3e9607d92b3697a661a6e7e9fbb65361846680d968cfc86c9561103 (5QkGjd5r...)), (CheckSpecVersion, CheckTxVersion, CheckGenesis, CheckMortality(Era::Mortal(64, 54)), CheckNonce(132), CheckWeight, ChargeTransactionPayment<0>, BaseFilter, ChargeExtraFee))), Call::XStaking(claim(Address::Id(31000d19a3e9607d92b3697a661a6e7e9fbb65361846680d968cfc86c9561103 (5QkGjd5r...)),)))] }
2020-12-07 13:28:51:556 INFO tokio-runtime-worker frame_executive  apply_extrinsic; ext=280404000b10a08d3b7601
2020-12-07 13:28:51:556 INFO tokio-runtime-worker frame_executive  apply_extrinsic; ext=2d0284ff31000d19a3e9607d92b3697a661a6e7e9fbb65361846680d968cfc86c9561103008f427051ca66838c0a3762e676102cdb1037b2edd1dff32e10cbcf3bcf064c820ae37f33a76c966b43c9904783b5baba1c69fa77eb206771b3e508fa3a5c120a65031102001b04ff31000d19a3e9607d92b3697a661a6e7e9fbb65361846680d968cfc86c9561103
2020-12-07 13:28:51:574 ERROR tokio-runtime-worker runtime  panicked at 'Transaction has a bad signature', /cargo-home/git/checkouts/substrate-7e08433d4c370a21/11ace4e/frame/executive/src/lib.rs:361:59
2020-12-07 13:28:51:574 WARN tokio-runtime-worker sc_service::client::client  Block prepare storage changes error:
Execution(Wasmi(Trap(Trap { kind: Unreachable })))
2020-12-07 13:28:51:574 WARN tokio-runtime-worker sync  💔 Error importing block 0x06edbf8187cf102e3e8d2f7d3a569353245e5694c9de255edb0906e766f96c50: Err(Other(ClientImport("Import failed: Execution failed: Wasmi(Trap(Trap { kind: Unreachable }))")))
2020-12-07 13:28:54:054 WARN tokio-runtime-worker telemetry  ❌ Error while dialing /dns/stats.chainx.org/tcp/1024/x-parity-ws/%2Fsubmit%2F: Custom { kind: Other, error: Other(B(A(Transport(Underlying(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))))) }
2020-12-07 13:28:54:821 INFO tokio-runtime-worker substrate  ⚙️  Syncing  0.0 bps, target=#178172 (5 peers), best: #177850 (0xef5f…6909), finalized #177849 (0x1913…fb14), ⬇ 50.1kiB/s ⬆ 5.1kiB/s
2020-12-07 13:28:57:230 INFO tokio-runtime-worker frame_executive  execute_block; block=Block { header: Header { parent_hash: 0x191380def78ba57f3a3e934e38f4977261c195ab3217956347dc78fffc76fb14, number: 177850, state_root: 0xceb79ec436fe107a6b75aee7e7e626a56f1a6a63f15ebab8d95f23123405ecb9, extrinsics_root: 0xe65569b3f8727f3ca0c60688710944884c67d5910f58154c10bd6c1292cc591f, digest: Digest { logs: [DigestItem::PreRuntime([66, 65, 66, 69], [3, 16, 0, 0, 0, 71, 158, 247, 15, 0, 0, 0, 0, 244, 170, 109, 177, 18, 103, 252, 139, 201, 236, 228, 168, 213, 204, 150, 97, 193, 248, 37, 72, 119, 39, 115, 117, 137, 33, 132, 51, 136, 16, 72, 114, 216, 84, 161, 84, 108, 114, 150, 182, 124, 223, 2, 4, 12, 62, 137, 86, 205, 148, 96, 201, 92, 77, 240, 68, 196, 112, 121, 140, 153, 150, 208, 2, 241, 160, 203, 70, 122, 18, 38, 147, 135, 47, 205, 64, 8, 224, 187, 208, 221, 73, 169, 173, 156, 62, 139, 243, 127, 225, 51, 189, 4, 128, 243, 2])] } }, extrinsics: [UncheckedExtrinsic(None, Call::Timestamp(set(1607316906000,))), UncheckedExtrinsic(Some((Address::Id(31000d19a3e9607d92b3697a661a6e7e9fbb65361846680d968cfc86c9561103 (5QkGjd5r...)), (CheckSpecVersion, CheckTxVersion, CheckGenesis, CheckMortality(Era::Mortal(64, 54)), CheckNonce(132), CheckWeight, ChargeTransactionPayment<0>, BaseFilter, ChargeExtraFee))), Call::XStaking(claim(Address::Id(31000d19a3e9607d92b3697a661a6e7e9fbb65361846680d968cfc86c9561103 (5QkGjd5r...)),)))] }
2020-12-07 13:28:57:230 INFO tokio-runtime-worker frame_executive  apply_extrinsic; ext=280404000b10a08d3b7601
2020-12-07 13:28:57:231 INFO tokio-runtime-worker frame_executive  apply_extrinsic; ext=2d0284ff31000d19a3e9607d92b3697a661a6e7e9fbb65361846680d968cfc86c9561103008f427051ca66838c0a3762e676102cdb1037b2edd1dff32e10cbcf3bcf064c820ae37f33a76c966b43c9904783b5baba1c69fa77eb206771b3e508fa3a5c120a65031102001b04ff31000d19a3e9607d92b3697a661a6e7e9fbb65361846680d968cfc86c9561103
2020-12-07 13:28:57:249 ERROR tokio-runtime-worker runtime  panicked at 'Transaction has a bad signature', /cargo-home/git/checkouts/substrate-7e08433d4c370a21/11ace4e/frame/executive/src/lib.rs:361:59
2020-12-07 13:28:57:249 WARN tokio-runtime-worker sc_service::client::client  Block prepare storage changes error:
Execution(Wasmi(Trap(Trap { kind: Unreachable })))
2020-12-07 13:28:57:250 WARN tokio-runtime-worker sync  💔 Error importing block 0x06edbf8187cf102e3e8d2f7d3a569353245e5694c9de255edb0906e766f96c50: Err(Other(ClientImport("Import failed: Execution failed: Wasmi(Trap(Trap { kind: Unreachable }))")))
2020-12-07 13:28:59:821 INFO tokio-runtime-worker substrate  ⚙️  Syncing  0.0 bps, target=#178172 (5 peers), best: #177850 (0xef5f…6909), finalized #177849 (0x1913…fb14), ⬇ 44.3kiB/s ⬆ 4.7kiB/s
2020-12-07 13:29:00:360 INFO tokio-runtime-worker frame_executive  execute_block; block=Block { header: Header { parent_hash: 0x191380def78ba57f3a3e934e38f4977261c195ab3217956347dc78fffc76fb14, number: 177850, state_root: 0xceb79ec436fe107a6b75aee7e7e626a56f1a6a63f15ebab8d95f23123405ecb9, extrinsics_root: 0xe65569b3f8727f3ca0c60688710944884c67d5910f58154c10bd6c1292cc591f, digest: Digest { logs: [DigestItem::PreRuntime([66, 65, 66, 69], [3, 16, 0, 0, 0, 71, 158, 247, 15, 0, 0, 0, 0, 244, 170, 109, 177, 18, 103, 252, 139, 201, 236, 228, 168, 213, 204, 150, 97, 193, 248, 37, 72, 119, 39, 115, 117, 137, 33, 132, 51, 136, 16, 72, 114, 216, 84, 161, 84, 108, 114, 150, 182, 124, 223, 2, 4, 12, 62, 137, 86, 205, 148, 96, 201, 92, 77, 240, 68, 196, 112, 121, 140, 153, 150, 208, 2, 241, 160, 203, 70, 122, 18, 38, 147, 135, 47, 205, 64, 8, 224, 187, 208, 221, 73, 169, 173, 156, 62, 139, 243, 127, 225, 51, 189, 4, 128, 243, 2])] } }, extrinsics: [UncheckedExtrinsic(None, Call::Timestamp(set(1607316906000,))), UncheckedExtrinsic(Some((Address::Id(31000d19a3e9607d92b3697a661a6e7e9fbb65361846680d968cfc86c9561103 (5QkGjd5r...)), (CheckSpecVersion, CheckTxVersion, CheckGenesis, CheckMortality(Era::Mortal(64, 54)), CheckNonce(132), CheckWeight, ChargeTransactionPayment<0>, BaseFilter, ChargeExtraFee))), Call::XStaking(claim(Address::Id(31000d19a3e9607d92b3697a661a6e7e9fbb65361846680d968cfc86c9561103 (5QkGjd5r...)),)))] }
2020-12-07 13:29:00:361 INFO tokio-runtime-worker frame_executive  apply_extrinsic; ext=280404000b10a08d3b7601
2020-12-07 13:29:00:361 INFO tokio-runtime-worker frame_executive  apply_extrinsic; ext=2d0284ff31000d19a3e9607d92b3697a661a6e7e9fbb65361846680d968cfc86c9561103008f427051ca66838c0a3762e676102cdb1037b2edd1dff32e10cbcf3bcf064c820ae37f33a76c966b43c9904783b5baba1c69fa77eb206771b3e508fa3a5c120a65031102001b04ff31000d19a3e9607d92b3697a661a6e7e9fbb65361846680d968cfc86c9561103
2020-12-07 13:29:00:380 ERROR tokio-runtime-worker runtime  panicked at 'Transaction has a bad signature', /cargo-home/git/checkouts/substrate-7e08433d4c370a21/11ace4e/frame/executive/src/lib.rs:361:59
2020-12-07 13:29:00:380 WARN tokio-runtime-worker sc_service::client::client  Block prepare storage changes error:
Execution(Wasmi(Trap(Trap { kind: Unreachable })))
2020-12-07 13:29:00:381 WARN tokio-runtime-worker sync  💔 Error importing block 0x06edbf8187cf102e3e8d2f7d3a569353245e5694c9de255edb0906e766f96c50: Err(Other(ClientImport("Import failed: Execution failed: Wasmi(Trap(Trap { kind: Unreachable }))")))
2020-12-07 13:29:01:593 INFO tokio-runtime-worker frame_executive  execute_block; block=Block { header: Header { parent_hash: 0x191380def78ba57f3a3e934e38f4977261c195ab3217956347dc78fffc76fb14, number: 177850, state_root: 0xceb79ec436fe107a6b75aee7e7e626a56f1a6a63f15ebab8d95f23123405ecb9, extrinsics_root: 0xe65569b3f8727f3ca0c60688710944884c67d5910f58154c10bd6c1292cc591f, digest: Digest { logs: [DigestItem::PreRuntime([66, 65, 66, 69], [3, 16, 0, 0, 0, 71, 158, 247, 15, 0, 0, 0, 0, 244, 170, 109, 177, 18, 103, 252, 139, 201, 236, 228, 168, 213, 204, 150, 97, 193, 248, 37, 72, 119, 39, 115, 117, 137, 33, 132, 51, 136, 16, 72, 114, 216, 84, 161, 84, 108, 114, 150, 182, 124, 223, 2, 4, 12, 62, 137, 86, 205, 148, 96, 201, 92, 77, 240, 68, 196, 112, 121, 140, 153, 150, 208, 2, 241, 160, 203, 70, 122, 18, 38, 147, 135, 47, 205, 64, 8, 224, 187, 208, 221, 73, 169, 173, 156, 62, 139, 243, 127, 225, 51, 189, 4, 128, 243, 2])] } }, extrinsics: [UncheckedExtrinsic(None, Call::Timestamp(set(1607316906000,))), UncheckedExtrinsic(Some((Address::Id(31000d19a3e9607d92b3697a661a6e7e9fbb65361846680d968cfc86c9561103 (5QkGjd5r...)), (CheckSpecVersion, CheckTxVersion, CheckGenesis, CheckMortality(Era::Mortal(64, 54)), CheckNonce(132), CheckWeight, ChargeTransactionPayment<0>, BaseFilter, ChargeExtraFee))), Call::XStaking(claim(Address::Id(31000d19a3e9607d92b3697a661a6e7e9fbb65361846680d968cfc86c9561103 (5QkGjd5r...)),)))] }
2020-12-07 13:29:01:594 INFO tokio-runtime-worker frame_executive  apply_extrinsic; ext=280404000b10a08d3b7601
2020-12-07 13:29:01:594 INFO tokio-runtime-worker frame_executive  apply_extrinsic; ext=2d0284ff31000d19a3e9607d92b3697a661a6e7e9fbb65361846680d968cfc86c9561103008f427051ca66838c0a3762e676102cdb1037b2edd1dff32e10cbcf3bcf064c820ae37f33a76c966b43c9904783b5baba1c69fa77eb206771b3e508fa3a5c120a65031102001b04ff31000d19a3e9607d92b3697a661a6e7e9fbb65361846680d968cfc86c9561103
2020-12-07 13:29:01:612 ERROR tokio-runtime-worker runtime  panicked at 'Transaction has a bad signature', /cargo-home/git/checkouts/substrate-7e08433d4c370a21/11ace4e/frame/executive/src/lib.rs:361:59
2020-12-07 13:29:01:612 WARN tokio-runtime-worker sc_service::client::client  Block prepare storage changes error:
Execution(Wasmi(Trap(Trap { kind: Unreachable })))

```

**Comment by koushiro** [comment]
we don't support ubuntu 16.04
