### ISSUE TITLE
JSsdk调用getAccountByBTCAddress报错

### ISSUE THREAD

**Issue by gifttang** [chainx-org/ChainX#58]
js调用getAccountByBTCAddress是报错。
看错误提示应该没有该RPC接口
![Uploading image.png…]()
(node:2125) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'apply' of undefined
    at Asset.getAccountByBTCAddress (/Users/gifttang/Documents/workspace/rust/CxProxy/node_modules/chainx.js/lib/Asset.js:51:82)
    at router.get (/Users/gifttang/Documents/workspace/rust/CxProxy/routes/chainx.js:50:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2125) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2125) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
GET /cx/asset - - ms - -

**Comment by aniiantt** [comment]
已删除
